
# Harvest Estimates {-}

```{r estimate-harvest}
# estimate (via bootstrap) set net harvest for all species and and strata
boot_out_set = bootstrap_harvest(interview_data, set_effort_info,
                                 gear = "set", n_boot = n_boot, stratify_interviews = FALSE)

# don't perform a drift net estimate, but create a placeholder data frame
boot_out_drift = boot_out_set
boot_out_drift[,c("chinook", "chum", "sockeye", "total")] = NA
boot_out_drift$gear = "drift"

# sum up across gears
boot_out_total = data.frame(iter = boot_out_drift$iter, 
                            date = boot_out_drift$date,
                            gear = "total", 
                            stratum = boot_out_drift$stratum,
                            chinook = rowSums(cbind(boot_out_drift[,"chinook"], boot_out_set[,"chinook"]), na.rm = TRUE),
                            chum = rowSums(cbind(boot_out_drift[,"chum"], boot_out_set[,"chum"]), na.rm = TRUE),
                            sockeye = rowSums(cbind(boot_out_drift[,"sockeye"], boot_out_set[,"sockeye"]), na.rm = TRUE),
                            total = rowSums(cbind(boot_out_drift[,"total"], boot_out_set[,"total"]), na.rm = TRUE)
)

# combine drift, set, and total into one data frame of bootstrap output
boot_out <<- rbind(boot_out_total, boot_out_drift, boot_out_set)
```

* An estimated total of **`r report()`** salmon were harvested.
  * An estimated total of **`r report(spp = "chinook")`** Chinook salmon were harvested.
  * An estimated total of **`r report(spp = "chum")`** chum salmon were harvested.
  * An estimated total of **`r report(spp = "sockeye")`** sockeye salmon were harvested.

```{r strata-summary-table}
make_strata_summary_table(interview_data, "set")
```
