
```{r}
appendix_counter = appendix_counter + 1
appendix_gear = ifelse(params$do_drift, "drift", "set")
```

\clearpage
\setcounter{figure}{0}
\setcounter{table}{0}
\renewcommand\thefigure{`r LETTERS[appendix_counter]`\arabic{figure}}
\renewcommand\thetable{`r LETTERS[appendix_counter]`\arabic{table}}

# Appendix `r LETTERS[appendix_counter]`: Non-salmon Harvest Information {-}

```{r estimate-harvest-nonsalmon}
# estimate (via bootstrap) drift net harvest for all species and and strata if requested
if (params$do_drift) {
  boot_out_drift = bootstrap_harvest(
    interview_data, drift_effort_info,
    gear = "drift", n_boot = params$n_boot,
    stratify_interviews = TRUE,
    nonsalmon = TRUE
  )
} else {
  boot_out_drift = NULL
}

# estimate (via bootstrap) set net harvest for all species and and strata if requested
if (params$do_set) {
  boot_out_set = bootstrap_harvest(
    interview_data, set_effort_info,
    gear = "set", n_boot = params$n_boot,
    stratify_interviews = FALSE,
    nonsalmon = TRUE
  )
} else {
  boot_out_set = NULL
}

# combine drift, set, and total into one data.frame of bootstrap output
boot_out <<- combine_boot_out(boot_out_drift = boot_out_drift, boot_out_set = boot_out_set)
```

```{r harvest-bullets-nonsalmon, results = "asis"}
harvest_bullets(include_set_summary = params$do_drift, nonsalmon = TRUE)
```

```{r}
make_strata_summary_table(interview_data, ifelse(params$do_drift, "drift", "set"), nonsalmon = TRUE)
```

```{r, results = "asis"}
make_appendix_tables(interview_data, gear = ifelse(params$do_drift, "drift", "set"), include_rates = FALSE, extra = NULL, nonsalmon = TRUE)
```
